=== arpan-g/data-analysis/sanac.dtd
<!ELEMENT sanac (model)>
<!ATTLIST sanac frame CDATA #REQUIRED>
<!ATTLIST sanac frameInfo CDATA #REQUIRED>
<!ELEMENT model (panel?, listOfCompartments, listOfSpecieClasses?, listOfSpecies, listOfReactions+, listOfWhiteBoxes?)>
<!ATTLIST model name CDATA #REQUIRED>
<!ATTLIST model modelInfo CDATA #IMPLIED>
<!ELEMENT panel EMPTY>
<!ATTLIST panel size CDATA #IMPLIED>
<!ATTLIST panel magnification CDATA #IMPLIED>
<!ELEMENT listOfCompartments (compartment+)>
<!ATTLIST listOfCompartments numberOfCompartments CDATA "1">
<!ELEMENT compartment (subCompartment+)>
<!ATTLIST compartment name CDATA #REQUIRED>
<!ATTLIST compartment volume CDATA #IMPLIED>
<!ATTLIST compartment R CDATA #IMPLIED>
<!ATTLIST compartment G CDATA #IMPLIED>
<!ATTLIST compartment B CDATA #IMPLIED>
<!ELEMENT subCompartment EMPTY>
<!ATTLIST subCompartment id CDATA #REQUIRED>
<!ATTLIST subCompartment cat CDATA #IMPLIED>
<!ATTLIST subCompartment cx CDATA #IMPLIED>
<!ATTLIST subCompartment cy CDATA #IMPLIED>
<!ATTLIST subCompartment l CDATA #IMPLIED>
<!ATTLIST subCompartment h CDATA #IMPLIED>
<!ATTLIST subCompartment w CDATA #IMPLIED>
<!ELEMENT listOfSpecieClasses (specieClass+)>
<!ELEMENT specieClass EMPTY>
<!ATTLIST specieClass R CDATA #IMPLIED>
<!ATTLIST specieClass G CDATA #IMPLIED>
<!ATTLIST specieClass B CDATA #IMPLIED>
<!ELEMENT listOfSpecies (Specie+)>
<!ATTLIST listOfSpecies numberOfSpecies CDATA "1">
<!ELEMENT Specie (specieAttribute, listOfElements?)>
<!ATTLIST Specie specieID CDATA #REQUIRED>
<!ATTLIST Specie name CDATA #REQUIRED>
<!ATTLIST Specie compartment CDATA #REQUIRED>
<!ELEMENT specieAttribute EMPTY>
<!ATTLIST specieAttribute specieClass CDATA #REQUIRED>
<!ATTLIST specieAttribute massBalance (on|off) "on">
<!ATTLIST specieAttribute totalAmount (variable|constant) "variable">
<!ATTLIST specieAttribute decomposition (on|off) "on">
<!ATTLIST specieAttribute initialAmount CDATA #IMPLIED>
<!ATTLIST specieAttribute isVisible (true|false) "true">
<!ELEMENT listOfElements (specieReference+)>
<!ATTLIST listOfElements numberOfElements CDATA "2">
<!ELEMENT specieReference (lineLocation?)>
<!ATTLIST specieReference specieID CDATA #REQUIRED>
<!ATTLIST specieReference name CDATA #REQUIRED>
<!ATTLIST specieReference compartment CDATA #REQUIRED>
<!ATTLIST specieReference stoichiometry CDATA "1">
<!ATTLIST specieReference cx CDATA #IMPLIED>
<!ATTLIST specieReference cy CDATA #IMPLIED>
<!ELEMENT lineLocation (segmentStatus*)>
<!ATTLIST lineLocation x1 CDATA #IMPLIED>
<!ATTLIST lineLocation x2 CDATA #IMPLIED>
<!ATTLIST lineLocation y1 CDATA #IMPLIED>
<!ATTLIST lineLocation y2 CDATA #IMPLIED>
<!ATTLIST lineLocation connectSegmentPoint CDATA #IMPLIED>
<!ELEMENT segmentStatus EMPTY>
<!ATTLIST segmentStatus counter CDATA #IMPLIED>
<!ATTLIST segmentStatus x CDATA #IMPLIED>
<!ATTLIST segmentStatus y CDATA #IMPLIED>
<!ELEMENT listOfReactions (Reaction+)>
<!ATTLIST listOfReactions layer (gene0|gene1|gene_other|protein|metabolic) "gene0">
<!ATTLIST listOfReactions numberOfReactions CDATA "1">
<!ELEMENT Reaction (listOfReactants, listOfProducts?, listOfModifiers?, modifierComplex?, lineLocation?, multiArmsReaction?)>
<!ATTLIST Reaction reactionID CDATA #REQUIRED>
<!ATTLIST Reaction groupID CDATA #REQUIRED>
<!ATTLIST Reaction reactionType CDATA #REQUIRED>
<!ATTLIST Reaction isConvertible (true|false) "true">
<!ATTLIST Reaction reactionName CDATA #REQUIRED>
<!ATTLIST Reaction isVisible (true|false) "true">
<!ATTLIST Reaction modifierReactionEquation CDATA #REQUIRED>
<!ELEMENT listOfReactants (specieReference*, reactionReference?)>
<!ATTLIST listOfReactants numberOfReactants CDATA "1">
<!ELEMENT reactionReference EMPTY>
<!ATTLIST reactionReference reactionID CDATA #REQUIRED>
<!ATTLIST reactionReference reactionName CDATA #REQUIRED>
<!ELEMENT listOfProducts (specieReference+)>
<!ATTLIST listOfProducts numberOfProducts CDATA "1">
<!ELEMENT listOfModifiers (modifierSpecieReference)>
<!ATTLIST listOfModifiers numberOfModifiers CDATA "1">
<!ELEMENT modifierSpecieReference (lineLocation?)>
<!ATTLIST modifierSpecieReference specieID CDATA #REQUIRED>
<!ATTLIST modifierSpecieReference name CDATA #REQUIRED>
<!ATTLIST modifierSpecieReference compartment CDATA #REQUIRED>
<!ATTLIST modifierSpecieReference stoichiometry CDATA "1">
<!ATTLIST modifierSpecieReference modifierType (enzyme|activator|inhibitor) #REQUIRED>
<!ATTLIST modifierSpecieReference isTotal CDATA #REQUIRED>
<!ATTLIST modifierSpecieReference cx CDATA #IMPLIED>
<!ATTLIST modifierSpecieReference cy CDATA #IMPLIED>
<!ELEMENT modifierComplex (specieReference)>
<!ELEMENT multiArmsReaction EMPTY>
<!ATTLIST multiArmsReaction cx CDATA #IMPLIED>
<!ATTLIST multiArmsReaction cy CDATA #IMPLIED>
<!ELEMENT listOfWhiteBoxes (whitebox+)>
<!ATTLIST listOfWhiteBoxes numberOfWhiteBoxes CDATA #REQUIRED>
<!ELEMENT whiteboxes (storedSpecie*, storedReaction*, storedModifier*, storedWhitebox*)>
<!ATTLIST whiteboxes whiteboxID CDATA #REQUIRED>
<!ATTLIST whiteboxes isCompression (true|false) "true">
<!ELEMENT storedSpecie EMPTY>
<!ATTLIST storedSpecie specieID CDATA #REQUIRED>
<!ATTLIST storedSpecie reactionID CDATA #REQUIRED>
<!ELEMENT storedReaction EMPTY>
<!ATTLIST storedReaction reactionID CDATA #REQUIRED>
<!ELEMENT storedModifier EMPTY>
<!ATTLIST storedModifier reactionID CDATA #REQUIRED>
<!ELEMENT storedWhitebox EMPTY>
<!ATTLIST storedWhitebox whiteboxID CDATA #REQUIRED>

=== arpan-g/data-analysis/HSR_demo.XML
<?xml version="1.0" encoding="SHIFT_JIS" standalone="no"?>
<!DOCTYPE sanac PUBLIC "sanac" "sanac.dtd">
<sanac frame="CADLIVE" frameInfo="2.14">
<model name="HSP13_0421" modelInfo="heat shock response model13">
<panel size="1600" magnification="100"/>
<listOfCompartments numberOfCompartments="2">
<compartment name="environment" volume="" R="255" G="255" B="255">
<subCompartment id="1" cat="Square" cx="-100" cy="-100" l="-1" h="80" w="80"/>
</compartment>
<compartment name="cytoplasm" volume="" R="224" G="224" B="255">
<subCompartment id="2" cat="Circle" cx="804" cy="772" l="708" h="-4" w="1416"/>
</compartment>
</listOfCompartments>
<listOfSpecies numberOfSpecies="29">
<Specie specieID="1" name="s70" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="2" name="RNAP" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="3" name="s32" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="4" name="FtsH" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="5" name="DnaK" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="6" name="Protein" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="7" name="Protein-f" compartment="cytoplasm">
<specieAttribute specieClass="protein" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="8" name="Enhancer(s32)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_enhancer" massBalance="on" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="9" name="Enhancer(HSP)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_enhancer" massBalance="on" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="10" name="D" compartment="cytoplasm">
<specieAttribute specieClass="DNA_others" massBalance="off" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="11" name="mRNA(s32)" compartment="cytoplasm">
<specieAttribute specieClass="RNA" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="12" name="mRNA(DnaK)" compartment="cytoplasm">
<specieAttribute specieClass="RNA" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="13" name="mRNA(FtsH)" compartment="cytoplasm">
<specieAttribute specieClass="RNA" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="14" name="mRNA(Protein)" compartment="cytoplasm">
<specieAttribute specieClass="RNA" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="15" name="Gene(s32)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_gene" massBalance="off" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="16" name="Gene(DnaK)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_gene" massBalance="off" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="17" name="Gene(FtsH)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_gene" massBalance="off" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="18" name="Gene(Protein)" compartment="cytoplasm">
<specieAttribute specieClass="DNA_gene" massBalance="off" totalAmount="constant" decomposition="off" initialAmount="" isVisible="true"/>
</Specie>
<Specie specieID="20" name="s70:RNAP" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="1" name="s70" compartment="cytoplasm" stoichiometry="1" cx="633" cy="481"/>
<specieReference specieID="2" name="RNAP" compartment="cytoplasm" stoichiometry="1" cx="633" cy="616"/>
</listOfElements>
</Specie>
<Specie specieID="22" name="Enhancer(s32):s70:RNAP" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="8" name="Enhancer(s32)" compartment="cytoplasm" stoichiometry="1" cx="687" cy="442"/>
<specieReference specieID="20" name="s70:RNAP" compartment="cytoplasm" stoichiometry="1" cx="633" cy="546"/>
</listOfElements>
</Specie>
<Specie specieID="23" name="RNAP:s32" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="2" name="RNAP" compartment="cytoplasm" stoichiometry="1" cx="633" cy="616"/>
<specieReference specieID="3" name="s32" compartment="cytoplasm" stoichiometry="1" cx="886" cy="616"/>
</listOfElements>
</Specie>
<Specie specieID="24" name="Enhancer(HSP):RNAP:s32" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="9" name="Enhancer(HSP)" compartment="cytoplasm" stoichiometry="1" cx="756" cy="753"/>
<specieReference specieID="23" name="RNAP:s32" compartment="cytoplasm" stoichiometry="1" cx="757" cy="616"/>
</listOfElements>
</Specie>
<Specie specieID="25" name="s32:DnaK" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="3" name="s32" compartment="cytoplasm" stoichiometry="1" cx="886" cy="616"/>
<specieReference specieID="5" name="DnaK" compartment="cytoplasm" stoichiometry="1" cx="1080" cy="794"/>
</listOfElements>
</Specie>
<Specie specieID="28" name="s32:FtsH" compartment="cytoplasm">
<specieAttribute specieClass="modifier_complex" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="false"/>
<listOfElements numberOfElements="2">
<specieReference specieID="3" name="s32" compartment="cytoplasm" stoichiometry="1" cx="886" cy="616"/>
<specieReference specieID="4" name="FtsH" compartment="cytoplasm" stoichiometry="1" cx="1036" cy="724"/>
</listOfElements>
</Specie>
<Specie specieID="29" name="Protein:DnaK" compartment="cytoplasm">
<specieAttribute specieClass="modifier_complex" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="false"/>
<listOfElements numberOfElements="2">
<specieReference specieID="6" name="Protein" compartment="cytoplasm" stoichiometry="1" cx="1209" cy="543"/>
<specieReference specieID="5" name="DnaK" compartment="cytoplasm" stoichiometry="1" cx="1080" cy="794"/>
</listOfElements>
</Specie>
<Specie specieID="30" name="D:s70:RNAP" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="10" name="D" compartment="cytoplasm" stoichiometry="1" cx="592" cy="749"/>
<specieReference specieID="20" name="s70:RNAP" compartment="cytoplasm" stoichiometry="1" cx="633" cy="546"/>
</listOfElements>
</Specie>
<Specie specieID="31" name="D:RNAP:s32" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="10" name="D" compartment="cytoplasm" stoichiometry="1" cx="592" cy="749"/>
<specieReference specieID="23" name="RNAP:s32" compartment="cytoplasm" stoichiometry="1" cx="757" cy="616"/>
</listOfElements>
</Specie>
<Specie specieID="32" name="RNAP:D" compartment="cytoplasm">
<specieAttribute specieClass="complex" massBalance="off" totalAmount="variable" decomposition="on" initialAmount="" isVisible="true"/>
<listOfElements numberOfElements="2">
<specieReference specieID="2" name="RNAP" compartment="cytoplasm" stoichiometry="1" cx="633" cy="616"/>
<specieReference specieID="10" name="D" compartment="cytoplasm" stoichiometry="1" cx="592" cy="749"/>
</listOfElements>
</Specie>
<Specie specieID="34" name="s32:DnaK:FtsH" compartment="cytoplasm">
<specieAttribute specieClass="modifier_complex" massBalance="on" totalAmount="variable" decomposition="on" initialAmount="" isVisible="false"/>
<listOfElements numberOfElements="2">
<specieReference specieID="25" name="s32:DnaK" compartment="cytoplasm" stoichiometry="1" cx="1080" cy="616"/>
<specieReference specieID="4" name="FtsH" compartment="cytoplasm" stoichiometry="1" cx="1036" cy="724"/>
</listOfElements>
</Specie>
</listOfSpecies>
<listOfReactions layer="gene" numberOfReactions="8">
<Reaction reactionID="10" groupID="4" reactionType="transcription" isConvertible="true" reactionName="#10" isVisible="true" modifierReactionEquation="Enhancer(s32):s70:RNAP -&gt;&gt; Gene(s32) -&gt; mRNA(s32)">
